# Generated by Django 3.1.5 on 2021-04-21 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateForAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointment', models.DateField(verbose_name='Дата записи')),
                ('month', models.IntegerField(default=0, verbose_name='Номер месяца')),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True, verbose_name='День недели')),
                ('day_of_week_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дня недели')),
                ('day_of_month_number', models.IntegerField(blank=True, null=True, verbose_name='Номер дня месяца')),
                ('is_holiday', models.BooleanField(verbose_name='Выходной')),
                ('is_sunday', models.BooleanField(default=False, verbose_name='Воскресенье')),
            ],
            options={
                'verbose_name': 'День записи',
                'verbose_name_plural': 'Дни записи',
                'ordering': ('date_appointment',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval', models.CharField(max_length=100, verbose_name='Временной интервал')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата рождения')),
                ('date_of_write', models.DateTimeField(blank=True, null=True, verbose_name='Дата записи')),
                ('is_booked', models.BooleanField(verbose_name='Забронировано')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к записи')),
                ('date_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.dateforappointment', verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Запись на тестирование',
                'verbose_name_plural': 'Записи на тестирование',
                'ordering': ('-date_appointment',),
            },
        ),
    ]
